source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/Malygos/zcprepo.git'

platform :ios, '9.0'
inhibit_all_warnings!

target:'Demo' do

# zcp
pod 'ZCPKit', '~> 0.0.2'
# 网络请求
pod 'AFNetworking', '~> 2.5.4'
# 图片加载
pod 'SDWebImage', '~> 4.1.0'
# 各种
pod 'YYKit', '~> 1.0.9'
# 键盘
pod 'IQKeyboardManager', '~> 5.0.2'
# swizzing
pod 'Aspects', '~> 1.4.1'
# 查找内存泄漏
pod 'MLeaksFinder', '~> 1.0.0'

end
