source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/Malygos/zcp-repos.git'

platform :ios, '9.0'
inhibit_all_warnings!

target:'Demo' do

# develop
pod 'ZCPCategory', :path => '~/Desktop/ZCPCode/ZCPCategory'
pod 'ZCPUtil', :path => '~/Desktop/ZCPCode/ZCPUtil'
pod 'ZCPGlobal', :path => '~/Desktop/ZCPCode/ZCPGlobal'
pod 'ZCPWebView', :path => '~/Desktop/ZCPCode/ZCPWebView'
pod 'ZCPUIKit', :path => '~/Desktop/ZCPCode/ZCPUIKit'
pod 'ZCPRouter', :path => '~/Desktop/ZCPCode/ZCPRouter'
pod 'ZCPNetwork', :path => '~/Desktop/ZCPCode/ZCPNetwork'
pod 'ZCPBaseClass', :path => '~/Desktop/ZCPCode/ZCPBaseClass'
pod 'ZCPCache', :path => '~/Desktop/ZCPCode/ZCPCache'

# zcp
#pod 'ZCPGlobal', '~> 0.0.1'
#pod 'ZCPCategory', '~> 0.0.1'
#pod 'ZCPUtil', '~> 0.0.1'
#pod 'ZCPWebView', '~> 0.0.1'
#pod 'ZCPUIKit', '~> 0.0.1'
#pod 'ZCPRouter', '~> 0.0.1'
#pod 'ZCPNetwork', '~> 0.0.1'
#pod 'ZCPBaseClass', '~> 0.0.1'
#pod 'ZCPCache', '~> 0.0.1'

# 网络请求
pod 'AFNetworking', '~> 3.2.1'
# 图片加载
pod 'SDWebImage'
pod 'SDWebImage/WebP'

# 各种
pod 'YYKit', '~> 1.0.9'
# 键盘
pod 'IQKeyboardManager', '~> 5.0.2'
# swizzing
pod 'Aspects', '~> 1.4.1'
# 查找内存泄漏
pod 'MLeaksFinder', '~> 1.0.0'
# 约束
pod 'Masonry', '~> 1.1.0'
# 滴滴 工具集合
pod 'DoraemonKit', '~> 1.1.7'


pod 'lottie-ios', '~> 2.5.3'
pod 'FLAnimatedImage'

end
