source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/Malygos/zcprepo.git'

platform :ios, '9.0'
inhibit_all_warnings!

target:'Demo' do

# zcp
pod 'ZCPKit', :git => 'https://gitlab.com/Malygos/ZCPKit.git'
pod 'ZCPUIKit', :git => 'https://gitlab.com/Malygos/ZCPUIKit.git'
# 网络请求
pod 'AFNetworking', '~> 3.2.1'
# 图片加载
pod 'SDWebImage', '~> 4.1.0'
# 各种
pod 'YYKit', '~> 1.0.9'
# 键盘
pod 'IQKeyboardManager', '~> 5.0.2'
# swizzing
pod 'Aspects', '~> 1.4.1'
# 查找内存泄漏
pod 'MLeaksFinder', '~> 1.0.0'
# 约束
pod 'Masonry', '~> 1.1.0'

# GUI
pod 'Texture', '~> 2.8'

# 滴滴 工具集合
pod 'DoraemonKit', '~> 1.1.7'

end
