# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlutterDemo

end

flutter_application_path = './flutter_demo'
fileJoin = File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
fileRead = File.read(fileJoin)
eval(fileRead, binding)